Vagrantfile for setting up a machine with pre-configured examples
ViDA-NYU/reprozip-examples pull request #6
Opened 2016-09-20 01:09 UTC by fchirigati

This provides updates to the Vagrantfile and to the installation script. It also updates the README files with instructions on how to run the examples in the machine.

All the examples were tested and work.
Packing with ReproZip has not been tested yet, but ReproZip is installed in the machine.

2016-09-20 01:11 UTC, fchirigati commented
@remram44 Could you try the machine? Also, feel free to make any modifications.

2016-09-20 15:34 UTC, remram44 commented on bechdel-test/bechdel.py
> +numbers_df['Released'] = pd.to_datetime(numbers_df['Released'])
Isn't it better to keep the original notebook's code, locking in the appropriate pandas version?

2016-09-20 15:37 UTC, remram44 commented on install.sh
> +wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
Can't the postgresql provided by Ubuntu be used? If this is for stacked-up, it's what I always used...

2016-09-20 15:37 UTC, remram44 commented on install.sh
> +sudo apt-get -y install python-dev build-essential
Here also, Ubuntu repositories provide pip & virtualenv...

2016-09-20 15:39 UTC, remram44 commented on install.sh
> +git clone https://github.com/opencv/opencv.git
Using OpenCV 2.4 (from Ubuntu) means we can use the original experiment code, don't have to compile and match the current RPZ file. Why the update? Compilation takes hours too...

2016-09-20 15:40 UTC, remram44 commented on Vagrantfile
> +        config.vm.network "forwarded_port", guest: 8000, host: 8111
Why change the port number?

2016-09-20 15:40 UTC, remram44 requested changes
This is really long to build (and failed when I tried) and uses weird versions that require changes to our examples.

2016-09-20 17:21 UTC, fchirigati commented on bechdel-test/bechdel.py
> +numbers_df['Released'] = pd.to_datetime(numbers_df['Released'])
I had already changed it back (check [here](https://github.com/ViDA-NYU/reprozip-examples/pull/6/commits/53a452231632ffa5e21fc524d9e197d06cb00372)). Do you happen to know why this is not being reflected? Perhaps when I moved the commits to a new branch I may have done something wrong?

2016-09-20 17:23 UTC, fchirigati commented on Vagrantfile
> +        config.vm.network "forwarded_port", guest: 8000, host: 8111
I wanted to be consistent with the original repository ([sdp_curricula](https://github.com/fchirigati/sdp_curricula)).

2016-09-20 17:36 UTC, fchirigati commented on install.sh
> +sudo apt-get -y install python-dev build-essential
pip: either way is fine for me.
virtualenv: I thought the regular way to install it was using pip (as I do).

2016-09-20 17:49 UTC, fchirigati commented on install.sh
> +git clone https://github.com/opencv/opencv.git
I don't know any other ways to install OpenCV -- does it come with the Ubuntu distribution? This was the standard compilation / installation step I found in many forums on the Web for Ubuntu. Let me know if there is any other way to install OpenCV.
Also, I did not have to chance any of the code for OpenCV 3.0.0, but you are right that it is better to use the same one from the RPZ package (I did not even realize that), so no issued on that.

2016-09-20 17:51 UTC, remram44 commented on bechdel-test/bechdel.py
> +numbers_df['Released'] = pd.to_datetime(numbers_df['Released'])
There's a lot of weird merges happening here, I'm not too sure what's up (that's also why I protected the branch).

2016-09-20 17:54 UTC, fchirigati commented on install.sh
> +wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
I had an issue with broken dependencies (as far as I remember), and some forums suggested to use this instead. But I was also using a different box, so I can try again.

2016-09-20 22:45 UTC, remram44 commented
Rewrote the Vagrant stuff, PostgreSQL is annoying. In particular in the Ubuntu box, systemd needs to be replaced by something else (upstart) which requires a reboot ([troubleshooting#systemd](http://reprozip.readthedocs.io/en/1.0.x/troubleshooting.html#systemd)).

2016-09-21 01:24 UTC, fchirigati commented
Any reasons for removing ReproZip from the machine? Isn't the main idea to try out the different examples with ReproZip?
Also, how come PostgreSQL 9.1 was working fine before (on my previous version and on the sdp_curricula repository)? Is this a matter of version (difference between 9.1 and 9.5)? Or perhaps they were doing something different in the original repository?

2016-09-21 01:26 UTC, fchirigati reviewed
Instructions on the README files probably need to be updated.

2016-09-21 18:11 UTC, remram44 approved these changes

2016-09-21 20:53 UTC, merged

2016-09-27 21:20 UTC, remram44 commented
After hours of investigation, I finally found the component that does the resizing: VBoxClient, started through `/etc/xdg/autostart`. I'm going to rebuild Vagrant machines for the demo and for vagrant with gui ([reprozip#191](https://github.com/ViDA-NYU/reprozip/pull/191)).

Another issue we have with the example VM is that it is too recent and therefore has PostgreSQL 9.5 while only 9.1 imports the stacked-up dump without warning (but it seems it runs fine anyway afterwards).